-- MySQL Script generated by MySQL Workbench
-- 02/23/16 11:09:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bus` DEFAULT CHARACTER SET utf8 ;
USE `bus` ;

-- -----------------------------------------------------
-- Table `bus`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`company` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `web` VARCHAR(300) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `logo` VARCHAR(300) NULL,
  `creation_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus`.`route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`route` (
  `route_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `name` VARCHAR(300) NOT NULL,
  `description` VARCHAR(500) NULL,
  `creation_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`route_id`, `company_id`),
  INDEX `fk_route_company1_idx` (`company_id` ASC),
  CONSTRAINT `fk_route_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `bus`.`company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus`.`bus_driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`bus_driver` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `bus_driver_id` INT NOT NULL,
  `driver_id` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `photo` VARCHAR(300) NULL,
  `creation_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`bus_driver_id`),
  INDEX `fk_bus_driver_company_idx` (`company_id` ASC),
  CONSTRAINT `fk_bus_driver_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `bus`.`company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus`.`bus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`bus` (
  `bus_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `route_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `license_plate` VARCHAR(45) NULL,
  `lat` DOUBLE NOT NULL,
  `lng` DOUBLE NOT NULL,
  `icon` VARCHAR(300) NOT NULL,
  `speed` VARCHAR(45) NULL,
  `state` VARCHAR(45) NOT NULL,
  `bus_driver_id` INT NULL,
  `creation_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`bus_id`, `company_id`, `route_id`),
  INDEX `fk_bus_bus_driver1_idx` (`bus_driver_id` ASC),
  INDEX `fk_bus_route1_idx` (`route_id` ASC, `company_id` ASC),
  CONSTRAINT `fk_bus_bus_driver1`
    FOREIGN KEY (`bus_driver_id`)
    REFERENCES `bus`.`bus_driver` (`bus_driver_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bus_route1`
    FOREIGN KEY (`route_id` , `company_id`)
    REFERENCES `bus`.`route` (`route_id` , `company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus`.`bus_stop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`bus_stop` (
  `bus_stop_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `route_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NULL,
  `lat` DOUBLE NOT NULL,
  `lng` DOUBLE NOT NULL,
  `icon` VARCHAR(300) NOT NULL,
  `creation_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`bus_stop_id`, `company_id`, `route_id`),
  INDEX `fk_bus_stop_route1_idx` (`route_id` ASC, `company_id` ASC),
  CONSTRAINT `fk_bus_stop_route1`
    FOREIGN KEY (`route_id` , `company_id`)
    REFERENCES `bus`.`route` (`route_id` , `company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`schedule` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `route_id` INT NOT NULL,
  `from` VARCHAR(45) NULL,
  `time` VARCHAR(45) NULL,
  `place` VARCHAR(45) NULL,
  `creation_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`schedule_id`),
  INDEX `fk_schedule_route1_idx` (`route_id` ASC, `company_id` ASC),
  CONSTRAINT `fk_schedule_route1`
    FOREIGN KEY (`route_id` , `company_id`)
    REFERENCES `bus`.`route` (`route_id` , `company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus`.`bus_extras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`bus_extras` (
  `bus_extras_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `route_id` INT NOT NULL,
  `bus_id` INT NOT NULL,
  `lat` DOUBLE NOT NULL,
  `lng` DOUBLE NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `time` TIMESTAMP NOT NULL,
  `capacity` INT NOT NULL,
  `kilometers` DOUBLE NOT NULL,
  PRIMARY KEY (`bus_extras_id`, `company_id`, `route_id`, `bus_id`),
  INDEX `fk_bus_extras_bus1_idx` (`bus_id` ASC, `company_id` ASC, `route_id` ASC),
  CONSTRAINT `fk_bus_extras_bus1`
    FOREIGN KEY (`bus_id` , `company_id` , `route_id`)
    REFERENCES `bus`.`bus` (`bus_id` , `company_id` , `route_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
