-- MySQL Script generated by MySQL Workbench
-- mié 02 mar 2016 12:14:45 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bus` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bus` ;

-- -----------------------------------------------------
-- Table `bus`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`company` (
  `company_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `address` VARCHAR(45) NOT NULL COMMENT '',
  `phone` VARCHAR(45) NOT NULL COMMENT '',
  `web` VARCHAR(300) NULL COMMENT '',
  `email` VARCHAR(100) NOT NULL COMMENT '',
  `password` VARCHAR(64) NOT NULL COMMENT '',
  `logo` VARCHAR(300) NULL COMMENT '',
  `creation_date` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`company_id`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus`.`route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`route` (
  `route_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `company_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(300) NOT NULL COMMENT '',
  `province` VARCHAR(45) NOT NULL COMMENT '',
  `description` VARCHAR(500) NULL COMMENT '',
  `creation_date` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`route_id`, `company_id`)  COMMENT '',
  INDEX `fk_route_company1_idx` (`company_id` ASC)  COMMENT '',
  CONSTRAINT `fk_route_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `bus`.`company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus`.`bus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`bus` (
  `bus_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `company_id` INT NOT NULL COMMENT '',
  `route_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `license_plate` VARCHAR(45) NULL COMMENT '',
  `lat` DOUBLE NOT NULL COMMENT '',
  `lng` DOUBLE NOT NULL COMMENT '',
  `icon` VARCHAR(300) NULL COMMENT '',
  `speed` VARCHAR(45) NOT NULL COMMENT '',
  `state` VARCHAR(45) NOT NULL COMMENT '',
  `creation_date` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`bus_id`, `company_id`, `route_id`)  COMMENT '',
  INDEX `fk_bus_route1_idx` (`route_id` ASC, `company_id` ASC)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '',
  CONSTRAINT `fk_bus_route1`
    FOREIGN KEY (`route_id` , `company_id`)
    REFERENCES `bus`.`route` (`route_id` , `company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus`.`bus_stop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`bus_stop` (
  `bus_stop_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `company_id` INT NOT NULL COMMENT '',
  `route_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `description` VARCHAR(500) NULL COMMENT '',
  `lat` DOUBLE NOT NULL COMMENT '',
  `lng` DOUBLE NOT NULL COMMENT '',
  `icon` VARCHAR(300) NULL COMMENT '',
  `creation_date` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`bus_stop_id`, `company_id`, `route_id`)  COMMENT '',
  INDEX `fk_bus_stop_route1_idx` (`route_id` ASC, `company_id` ASC)  COMMENT '',
  CONSTRAINT `fk_bus_stop_route1`
    FOREIGN KEY (`route_id` , `company_id`)
    REFERENCES `bus`.`route` (`route_id` , `company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`schedule` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `company_id` INT NOT NULL COMMENT '',
  `route_id` INT NOT NULL COMMENT '',
  `from` VARCHAR(45) NULL COMMENT '',
  `time` VARCHAR(45) NULL COMMENT '',
  `place` VARCHAR(45) NULL COMMENT '',
  `creation_date` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`schedule_id`)  COMMENT '',
  INDEX `fk_schedule_route1_idx` (`route_id` ASC, `company_id` ASC)  COMMENT '',
  CONSTRAINT `fk_schedule_route1`
    FOREIGN KEY (`route_id` , `company_id`)
    REFERENCES `bus`.`route` (`route_id` , `company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus`.`bus_extras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`bus_extras` (
  `bus_extras_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `company_id` INT NOT NULL COMMENT '',
  `route_id` INT NOT NULL COMMENT '',
  `bus_id` INT NOT NULL COMMENT '',
  `lat` DOUBLE NOT NULL COMMENT '',
  `lng` DOUBLE NOT NULL COMMENT '',
  `state` VARCHAR(45) NOT NULL COMMENT '',
  `capacity` INT NULL COMMENT '',
  `speed` DOUBLE NOT NULL COMMENT '',
  `kilometers` DOUBLE NOT NULL COMMENT '',
  `time` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`bus_extras_id`, `company_id`, `route_id`, `bus_id`)  COMMENT '',
  INDEX `fk_bus_extras_bus1_idx` (`bus_id` ASC, `company_id` ASC, `route_id` ASC)  COMMENT '',
  CONSTRAINT `fk_bus_extras_bus1`
    FOREIGN KEY (`bus_id` , `company_id` , `route_id`)
    REFERENCES `bus`.`bus` (`bus_id` , `company_id` , `route_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus`.`bus_driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`bus_driver` (
  `bus_driver_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `company_id` INT NOT NULL COMMENT '',
  `driver_id` VARCHAR(45) NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `lastname` VARCHAR(45) NULL COMMENT '',
  `phone` VARCHAR(45) NULL COMMENT '',
  `photo` VARCHAR(300) NULL COMMENT '',
  `creation_date` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`bus_driver_id`)  COMMENT '',
  INDEX `fk_bus_driver_company_idx` (`company_id` ASC)  COMMENT '',
  CONSTRAINT `fk_bus_driver_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `bus`.`company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
