-- MySQL Script generated by MySQL Workbench
-- mié 02 mar 2016 14:46:36 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bus_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bus_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bus_test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bus_test` ;

-- -----------------------------------------------------
-- Table `bus_test`.`route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_test`.`route` (
  `route_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `company_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(300) NOT NULL COMMENT '',
  `province` VARCHAR(45) NOT NULL COMMENT '',
  `description` VARCHAR(500) NULL COMMENT '',
  `creation_date` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`route_id`, `company_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_test`.`bus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_test`.`bus` (
  `bus_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `company_id` INT NOT NULL COMMENT '',
  `route_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `license_plate` VARCHAR(45) NULL COMMENT '',
  `lat` DOUBLE NOT NULL COMMENT '',
  `lng` DOUBLE NOT NULL COMMENT '',
  `icon` VARCHAR(300) NULL COMMENT '',
  `speed` VARCHAR(45) NOT NULL COMMENT '',
  `state` VARCHAR(45) NOT NULL COMMENT '',
  `creation_date` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`bus_id`, `company_id`, `route_id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_test`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_test`.`company` (
  `company_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `address` VARCHAR(45) NOT NULL COMMENT '',
  `phone` VARCHAR(45) NOT NULL COMMENT '',
  `web` VARCHAR(300) NULL COMMENT '',
  `email` VARCHAR(100) NOT NULL COMMENT '',
  `password` VARCHAR(64) NOT NULL COMMENT '',
  `logo` VARCHAR(300) NULL COMMENT '',
  `creation_date` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`company_id`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_test`.`bus_stop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_test`.`bus_stop` (
  `bus_stop_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `company_id` INT NOT NULL COMMENT '',
  `route_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `description` VARCHAR(500) NULL COMMENT '',
  `lat` DOUBLE NOT NULL COMMENT '',
  `lng` DOUBLE NOT NULL COMMENT '',
  `icon` VARCHAR(300) NULL COMMENT '',
  `creation_date` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`bus_stop_id`, `company_id`, `route_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_test`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_test`.`schedule` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `company_id` INT NOT NULL COMMENT '',
  `route_id` INT NOT NULL COMMENT '',
  `from` VARCHAR(45) NULL COMMENT '',
  `time` VARCHAR(45) NULL COMMENT '',
  `place` VARCHAR(45) NULL COMMENT '',
  `creation_date` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`schedule_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_test`.`bus_extras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_test`.`bus_extras` (
  `bus_extras_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `company_id` INT NOT NULL COMMENT '',
  `route_id` INT NOT NULL COMMENT '',
  `bus_id` INT NOT NULL COMMENT '',
  `lat` DOUBLE NOT NULL COMMENT '',
  `lng` DOUBLE NOT NULL COMMENT '',
  `state` VARCHAR(45) NOT NULL COMMENT '',
  `capacity` INT NULL COMMENT '',
  `speed` DOUBLE NOT NULL COMMENT '',
  `kilometers` DOUBLE NOT NULL COMMENT '',
  `time` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`bus_extras_id`, `company_id`, `route_id`, `bus_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_test`.`bus_driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_test`.`bus_driver` (
  `bus_driver_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `company_id` INT NOT NULL COMMENT '',
  `driver_id` VARCHAR(45) NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `lastname` VARCHAR(45) NULL COMMENT '',
  `phone` VARCHAR(45) NULL COMMENT '',
  `photo` VARCHAR(300) NULL COMMENT '',
  `creation_date` TIMESTAMP NOT NULL COMMENT '',
  PRIMARY KEY (`bus_driver_id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
