-- MySQL Script generated by MySQL Workbench
-- mié 17 feb 2016 21:23:32 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gmaps
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gmaps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gmaps` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `gmaps` ;

-- -----------------------------------------------------
-- Table `gmaps`.`markers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gmaps`.`markers` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `description` VARCHAR(45) NULL COMMENT '',
  `lat` DOUBLE NULL COMMENT '',
  `lng` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
